"""Run the whole platform end to end.

    python pipeline.py            # build source if missing, then load, transform, certify, report
    python pipeline.py --fresh    # rebuild the synthetic CRM and warehouse from scratch

Steps:
  1. source      synthetic CRM (stands in for the real operational system)
  2. ingest      incremental extract-load into the warehouse raw layer
  3. transform   dbt build: staging -> certified -> metrics, with every test
  4. certify     validate the KPI Bible against the certified warehouse
  5. report      executive dashboard from certified KPIs only
Any failed test or invalid KPI stops the run before reporting.
"""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

from source.generate_crm import build as build_source  # noqa: E402
from ingestion.extract_load import extract_load  # noqa: E402

SOURCE = ROOT / "data/crm.sqlite"
WAREHOUSE = ROOT / "data/warehouse.duckdb"


def step(name: str):
    print(f"\n== {name} " + "=" * (60 - len(name)))
    return time.time()


def run_dbt() -> dict:
    env = {**os.environ, "WAREHOUSE_PATH": str(WAREHOUSE)}
    proc = subprocess.run(
        ["dbt", "build", "--project-dir", "transform", "--profiles-dir", "transform"],
        cwd=ROOT, env=env, capture_output=True, text=True,
    )
    results = json.loads((ROOT / "transform/target/run_results.json").read_text())["results"]
    summary = {"models": 0, "tests_passed": 0, "tests_failed": 0}
    for r in results:
        if r["unique_id"].startswith("model."):
            summary["models"] += 1
        elif r["status"] == "pass":
            summary["tests_passed"] += 1
        else:
            summary["tests_failed"] += 1
    if proc.returncode != 0:
        print(proc.stdout[-3000:])
        raise SystemExit("dbt build failed: fix the failing tests above before anything is reported.")
    return summary


def write_run_report(loaded: dict, dbt: dict) -> None:
    import duckdb

    con = duckdb.connect(str(WAREHOUSE), read_only=True)
    tables = con.execute(
        "SELECT schema_name, table_name FROM duckdb_tables() "
        "WHERE schema_name IN ('raw', 'certified', 'metrics') ORDER BY 1, 2"
    ).fetchall()
    layers = [(s, t, con.execute(f"SELECT COUNT(*) FROM {s}.{t}").fetchone()[0]) for s, t in tables]
    con.close()
    rows = "\n".join(f"| {s} | `{t}` | {n:,} |" for s, t, n in layers)
    (ROOT / "docs/last_run.md").write_text(
        "# Last pipeline run\n\n*Generated by `pipeline.py`.*\n\n"
        f"- Rows ingested this run: {sum(loaded.values()):,}\n"
        f"- dbt models built: {dbt['models']}\n"
        f"- Data tests passed: {dbt['tests_passed']} (failed: {dbt['tests_failed']})\n\n"
        "| Layer | Table | Rows |\n| --- | --- | --- |\n" + rows + "\n"
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--fresh", action="store_true", help="rebuild source and warehouse")
    a = ap.parse_args()
    t0 = time.time()

    if a.fresh:
        WAREHOUSE.unlink(missing_ok=True)
    if a.fresh or not SOURCE.exists():
        step("1. source")
        print(build_source(SOURCE))

    step("2. ingest")
    loaded = extract_load(SOURCE, WAREHOUSE)
    for t, n in loaded.items():
        print(f"  {t:<14}{n:>8,} new rows")

    step("3. transform + test")
    dbt = run_dbt()
    print(f"  {dbt['models']} models built, {dbt['tests_passed']} tests passed")

    step("4. certify KPIs")
    subprocess.run([sys.executable, "kpis/validate_kpis.py"], cwd=ROOT, check=True)

    step("5. report")
    from dashboard.build_dashboard import build as build_dashboard
    build_dashboard(WAREHOUSE, ROOT / "docs")
    write_run_report(loaded, dbt)
    print("  docs/dashboard.html, docs/img/dashboard_preview.png, docs/last_run.md")

    print(f"\nDone in {time.time() - t0:.1f}s")


if __name__ == "__main__":
    main()
